# Generated by Django 4.1 on 2024-03-27 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chadebebe', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='presente',
            name='nomme',
        ),
        migrations.AddField(
            model_name='presente',
            name='nome',
            field=models.CharField(default=0, max_length=70),
            preserve_default=False,
        ),
    ]
