# Generated by Django 4.1 on 2024-03-27 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chadebebe', '0002_remove_presente_nomme_presente_nome'),
    ]

    operations = [
        migrations.AddField(
            model_name='presente',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
    ]
