# Generated by Django 4.1 on 2022-08-11 19:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='refeicoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refeicao', models.TextField()),
                ('data_refeicao', models.DateTimeField(auto_now=True, verbose_name='Data da Refeição')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='Criado em.')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='createdbyclient', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
            ],
        ),
    ]
