# Generated by Django 4.1 on 2022-08-11 20:22

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('nutri', '0004_rename_refeicoes_refeicoess'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Refeicoess',
            new_name='Refeicoes',
        ),
    ]
