# Generated by Django 4.1 on 2022-08-11 20:36

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('nutri', '0005_rename_refeicoess_refeicoes'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Refeicoes',
            new_name='Consumo',
        ),
    ]
