# Generated by Django 4.1 on 2022-08-11 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutri', '0006_rename_refeicoes_consumo'),
    ]

    operations = [
        migrations.CreateModel(
            name='teste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testeaa', models.TextField()),
            ],
        ),
    ]
