# Generated by Django 4.1 on 2022-08-11 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nutri', '0007_teste'),
    ]

    operations = [
        migrations.DeleteModel(
            name='teste',
        ),
    ]
