# Generated by Django 4.1 on 2023-02-03 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutri', '0008_delete_teste'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumo',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Criado em.'),
        ),
    ]
